// ============================================================
// Word & Sentence Banks for all game modes
// ============================================================

export const wordBank = {
  // ── Single Word Mode ──────────────────────────────────────
  words: {
    easy: [
      "the", "run", "cat", "dog", "sun", "map", "pen", "box", "hat", "cup",
      "red", "big", "hop", "sit", "top", "fun", "hot", "let", "hit", "win",
      "go", "fix", "mix", "zip", "jam", "jet", "fog", "mud", "tap", "rim",
      "oak", "dip", "cot", "den", "fin", "gum", "hen", "jot", "kit", "lag",
      "mat", "nap", "oar", "pad", "rag", "sap", "van", "wax", "yam", "zen",
      "ape", "bay", "cod", "dew", "elm", "fig", "gap", "hue", "ivy", "jay",
      "key", "lip", "mop", "net", "owl", "pie", "ram", "ski", "tie", "urn",
    ],
    medium: [
      "bridge", "planet", "forest", "garden", "silver", "frozen", "castle",
      "bottle", "hammer", "basket", "candle", "mirror", "pillow", "shadow",
      "stream", "temple", "violet", "anchor", "beacon", "cipher", "dagger",
      "falcon", "goblet", "hunter", "island", "jungle", "knight", "lumber",
      "marble", "needle", "osprey", "pirate", "quartz", "rocket", "saddle",
      "throne", "upward", "velvet", "walrus", "yogurt", "zenith", "border",
      "clover", "desert", "engine", "flight", "gravel", "hollow", "insect",
      "jumble", "kennel", "locket", "muzzle", "nibble", "orchid", "paddle",
      "quiver", "riddle", "sculpt", "tangle", "unique", "vortex", "wander",
      "export", "zephyr", "combat", "breeze", "floral", "mystic", "summit",
    ],
    hard: [
      "algorithm", "labyrinth", "threshold", "caterpillar", "chandelier",
      "bankruptcy", "surveillance", "phenomenon", "quintessential", "bureaucracy",
      "asynchronous", "metamorphosis", "psychological", "infrastructure",
      "cryptocurrency", "philosophical", "unprecedented", "electromagnetic",
      "juxtaposition", "onomatopoeia", "serendipity", "kaleidoscope",
      "extraterrestrial", "authentication", "biodegradable", "circumference",
      "disambiguation", "equilibrium", "fluorescence", "hallucination",
      "idiosyncratic", "jurisdictional", "knowledgeable", "miscellaneous",
      "neuroscience", "overwhelming", "perpendicular", "revolutionary",
      "subconscious", "thermodynamics", "understanding", "vulnerability",
      "xylophone", "accomplishment", "bioluminescence", "conscientious",
      "deterioration", "entrepreneurship", "fortification", "gravitational",
      "hypothetical", "incomprehensible", "photosynthesis", "transcontinental",
      "reconnaissance", "sophisticated", "transformation", "unbelievable",
      "visualization", "weatherproof", "approximately", "configuration",
    ],
  },

  // ── Sentence Mode ─────────────────────────────────────────
  sentences: {
    // Easy: ~30–50 characters, simple structure
    easy: [
      "The cat sat on the warm mat",
      "She ran fast to catch the bus",
      "A big red fox hid in the woods",
      "He put the cup on the table",
      "The sun set behind the hills",
      "I love to read books at night",
      "The bird sang a sweet melody",
      "We ran through the green park",
      "The wind blew the leaves away",
      "She smiled and waved goodbye",
      "A small dog played in the yard",
      "The lake was calm and still",
      "He found a coin on the ground",
      "The train left the station",
      "They built a house from bricks",
      "A cold breeze swept the shore",
      "The moon lit up the dark sky",
      "She drew a picture of a tree",
      "He fixed the broken old chair",
      "The bell rang at noon today",
    ],
    // Medium: ~50–80 characters, basic punctuation
    medium: [
      "She quickly grabbed her coat and ran to the bus stop.",
      "The bright sun slowly set behind the distant mountains.",
      "He decided to learn a new language over the summer break.",
      "The old bookshop on the corner had a wonderful collection.",
      "They walked along the river and watched the boats pass by.",
      "A gentle rain started falling just as we reached the cafe.",
      "The garden was full of colorful flowers and butterflies.",
      "She practiced the piano every day for almost two hours.",
      "The team worked together to finish the project on time.",
      "He opened the window to let the cool morning air inside.",
      "The children laughed and played in the golden autumn leaves.",
      "A mysterious letter arrived with no return address on it.",
      "The lighthouse stood tall against the crashing ocean waves.",
      "She baked a delicious chocolate cake for her best friend.",
      "The library was quiet except for the soft turning of pages.",
      "He climbed the hill to get a better view of the sunset.",
      "The street performer drew a large crowd with her singing.",
      "A curious fox appeared at the edge of the snowy forest.",
      "The clock tower chimed twelve times at the stroke of noon.",
      "She found an old map hidden inside the dusty wooden chest.",
    ],
    // Hard: ~80–120 characters, complex with mixed punctuation
    hard: [
      "Despite the heavy rain, the determined hikers pressed on through the winding mountain trail.",
      "The professor's lecture on quantum mechanics left the students both fascinated and bewildered.",
      "After years of research, the scientists finally published their groundbreaking discovery in nature.",
      "The ancient manuscript, written in a forgotten language, held secrets of a long-lost civilization.",
      "She juggled multiple responsibilities at work while pursuing her graduate degree in the evenings.",
      "The city's infrastructure had deteriorated significantly, requiring billions in emergency repairs.",
      "A breakthrough in renewable energy technology promised to revolutionize the global power industry.",
      "The orchestra performed a breathtaking symphony that received a standing ovation from the audience.",
      "Navigating through the dense fog, the captain relied entirely on instruments to guide the vessel.",
      "The documentary explored the complex relationship between technology, privacy, and modern society.",
      "Despite numerous setbacks and obstacles, the startup eventually became a billion-dollar enterprise.",
      "The archaeologists carefully excavated the site, uncovering artifacts from the Bronze Age period.",
      "Her extraordinary talent for mathematics was evident from a remarkably young age, surprising everyone.",
      "The international summit brought together leaders from over fifty nations to discuss climate change.",
      "After a grueling twelve-hour negotiation, both parties finally reached a mutually beneficial agreement.",
      "The novelist spent decades perfecting her craft before publishing her critically acclaimed masterpiece.",
      "Quantum computing represents a fundamental shift in how we approach complex computational problems.",
      "The vast coral reef ecosystem supports thousands of marine species in a delicate natural balance.",
      "Artificial intelligence continues to reshape industries, creating both opportunities and challenges.",
      "The expedition team documented rare wildlife species deep within the unexplored Amazonian rainforest.",
    ],
  },

  // ── Story Mode ────────────────────────────────────────────
  storyMode: [
    {
      stage: 1,
      title: "The Awakening",
      sentences: [
        "You open your eyes in a quiet village.",
        "A messenger arrives with urgent news.",
        "Dark forces have invaded the kingdom.",
        "You must prove your worth at the arena.",
        "The battle begins now.",
      ],
    },
    {
      stage: 2,
      title: "The Forest Path",
      sentences: [
        "You set out on the winding forest trail.",
        "Strange sounds echo through the tall trees.",
        "A shadowy figure blocks the narrow path ahead.",
        "You steel your nerves and prepare for battle.",
        "Only your speed can save you here.",
      ],
    },
    {
      stage: 3,
      title: "The Dark Cavern",
      sentences: [
        "The cavern entrance yawns before you like a mouth.",
        "Water drips from ancient stalactites overhead.",
        "Glowing crystals line the walls of the deep tunnel.",
        "A growl reverberates from somewhere in the darkness.",
        "You grip your weapon and step into the unknown.",
        "Each keystroke echoes like thunder in this place.",
      ],
    },
    {
      stage: 4,
      title: "The Ruined Bridge",
      sentences: [
        "A massive stone bridge stretches across a bottomless gorge.",
        "Half of the bridge has crumbled into the void below.",
        "An armored sentinel guards the remaining narrow passage.",
        "The wind howls as you approach the crumbling stone edge.",
        "You must type faster than ever to cross safely.",
        "One mistake could send you tumbling into the abyss.",
      ],
    },
    {
      stage: 5,
      title: "The Sorcerer's Tower",
      sentences: [
        "A spiraling tower of black stone rises into the stormy sky above.",
        "Lightning cracks and illuminates strange runes on the ancient walls.",
        "The sorcerer watches you from the highest window of the tower.",
        "Magical barriers test your speed as you climb each winding staircase.",
        "Energy pulses through the air with every correct word you type.",
        "The sorcerer laughs as the challenges grow increasingly difficult.",
        "You will not be stopped by mere parlor tricks and illusions.",
      ],
    },
    {
      stage: 6,
      title: "The Frozen Wastes",
      sentences: [
        "A blizzard rages across the endless frozen tundra stretching before you.",
        "Your fingers are numb but your determination burns like an inner fire.",
        "Ice golems rise from the frozen ground and block your treacherous path.",
        "Each correctly typed word melts the frost that creeps across your screen.",
        "The cold saps your energy but you refuse to slow down or surrender.",
        "Somewhere beyond the howling storm lies the entrance to the next trial.",
        "You push forward through the blinding white fury of the winter storm.",
      ],
    },
    {
      stage: 7,
      title: "The Labyrinth of Echoes",
      sentences: [
        "Twisting corridors stretch endlessly in every direction around you now.",
        "The walls seem to shift and rearrange themselves when you are not looking.",
        "Echoes of your own typing return to you as distorted whispers in the dark.",
        "A minotaur prowls the maze searching for intruders who dare enter its domain.",
        "You must maintain perfect accuracy to find the one true path through the maze.",
        "Wrong turns cost precious time that you simply cannot afford to lose here.",
        "The exit glimmers faintly at the end of a long and narrow corridor ahead.",
      ],
    },
    {
      stage: 8,
      title: "The Volcanic Forge",
      sentences: [
        "Rivers of molten lava flow beneath the narrow stone platforms you must cross carefully.",
        "The heat is unbearable and sweat drips onto your keyboard as you type each word.",
        "Ancient dwarven machinery clanks and groans in the depths of this volcanic stronghold.",
        "A fire drake guards the legendary forge where the ultimate weapon awaits its master.",
        "Your typing speed must match the relentless rhythm of the hammers pounding hot steel.",
        "Sparks fly with every keystroke as the forge responds to your unwavering determination.",
        "The drake roars in fury as you prove yourself worthy of the enchanted blade at last.",
      ],
    },
    {
      stage: 9,
      title: "The Shadow Realm",
      sentences: [
        "Reality itself seems to warp and bend as you step through the dark portal into shadow.",
        "Shadows take the form of your greatest fears and manifest as formidable typing challenges.",
        "The boundary between what is real and what is illusion has become impossible to discern.",
        "Your shadow self appears before you as a mirror image and challenges you to a final duel.",
        "Only by typing with absolute precision and blazing speed can you overcome your own darkness.",
        "The realm trembles as your keystrokes shatter the illusions one by one with growing force.",
        "Light begins to break through the shadow as you approach the gateway to the final battle.",
        "You have conquered your deepest fears and emerge stronger than you have ever been before.",
      ],
    },
    {
      stage: 10,
      title: "The Throne of the Tyrant",
      sentences: [
        "The tyrant's obsidian throne room stretches before you in all its dark and terrible glory.",
        "Pillars of corrupted crystal pulse with malevolent energy that fills the enormous chamber.",
        "The tyrant rises from the throne, fingers crackling with the power of a thousand dark spells.",
        "This is the ultimate test of everything you have learned on your long and arduous journey.",
        "Every word you type channels the combined strength of all the allies you have made along the way.",
        "The tyrant fights back with supernatural speed but your determination is absolutely unbreakable.",
        "Keystroke by keystroke you dismantle the tyrant's defenses and push closer to total victory.",
        "With one final burst of incredible speed, you strike the decisive blow that ends the reign of terror.",
      ],
    },
  ],
};
